
version: '3.8'

services:
  db:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file:
      - env/mysql.env
    ports:
      - '3306:3306'
    expose:
      - '3306'